<a href="https://colab.research.google.com/github/marekhennig/175IC-machine-learning/blob/main/Zad_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy
import pandas as pd
import sklearn
from sklearn import preprocessing

data = {
    'size': ['L', 'M','S','S','M','M','M','L','L','S'],
    'color': ['green', 'red', 'blue','black', 'black','yellow', 'pink', 'brown', 'black', 'white'],
    'gender': ['female', 'male','female','male','female','male','female','female','male','female'],
    'price': [147.99, 54.50, 100.00, 120.00, 20.00,240.00, 140.88, 37.21, 99.99, 84.20],
    'weight': [488.00, 420.00, 120.00, 200.00, 220.00,180.00,240.00,300.00,400.00, 390.00],
    'bought': ['no', 'no','no', 'yes','no', 'no','yes', 'yes','yes', 'yes']
}
df_raw = pd.DataFrame(data=data)
df = df_raw.copy()
#df.info()
for col in ['size', 'color', 'gender', 'bought']:
    df[col] = df[col].astype('category')
df.info()
df.describe(include=['category']).T

le = preprocessing.LabelEncoder()
le.fit_transform(df['bought'])
le.classes_
pd.get_dummies(data=df)
df = pd.get_dummies(data=df, drop_first=True)
scaler = preprocessing.StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    10 non-null     category
 1   color   10 non-null     category
 2   gender  10 non-null     category
 3   price   10 non-null     float64
 4   weight  10 non-null     float64
 5   bought  10 non-null     category
dtypes: category(4), float64(2)
memory usage: 1008.0 bytes

      price    weight  size_M  ...  color_yellow  gender_male  bought_yes
0  0.720862  1.657466       0  ...             0            0           0
1 -0.827949  1.071057       1  ...             0            1           0
2 -0.074169 -1.516038       0  ...             0            0           0
3  0.257163 -0.826146       0  ...             0            1           1
4 -1.399496 -0.653673       1  ...             0            0           0
5  2.245154 -0.998619       1  ...             1            1           0
6  0.603074 -0.481200       1  ...             0            0           1
7 -1.114385  0.036219       0  ...             0            0           1
8 -0.074334  0.898584       0  ...             0            1           1
9 -0.335921  0.812348       0  ...             0            0           1

[10 rows x 13 columns]